apiVersion: apps/v1
kind: Deployment
metadata:
  name: toggen-socket-load-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toggen-socket-load-client
  template:
    metadata:
      labels:
        app: toggen-socket-load-client
    spec:
      containers:
        - name: toggen-socket-load-client
          image: ridvanuyn/toggen-socket-load-client:latest
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: toggen-socket-load-client-service
spec:
  selector:
    app: toggen-socket-load-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3001
  type: LoadBalancer

---